### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by chenjiajun1984** [giscafer/FinalScheduler#15]
17-Oct-2019 09:59:16.192 信息 [http-nio-8080-exec-7] org.directwebremoting.impl.StartupUtil.logStartup Starting: DwrServlet v3.0.0.116.rc1 on Apache Tomcat/8.5.47 / JDK 1.8.0_121 from Oracle Corporation at /FinalScheduler_Web_exploded
17-Oct-2019 09:59:16.957 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DTDEntityResolver.resolveEntity Deprecated public id in dwr.xml. Use: <!DOCTYPE dwr PUBLIC "-//GetAhead Limited//DTD Direct Web Remoting 3.0//EN" "http://getahead.org/dwr//dwr30.dtd">
17-Oct-2019 09:59:16.957 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Clash of converters for java.util.Map. Using org.directwebremoting.convert.MapConverter in place of org.directwebremoting.convert.MapConverter
17-Oct-2019 09:59:16.957 信息 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Probably not an issue: java.util.List is not available so the list converter will not load. This is only an problem if you wanted to use it.
17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Clash of converters for java.util.Collection. Using org.directwebremoting.convert.CollectionConverter in place of org.directwebremoting.convert.CollectionConverter
17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.SignatureParser.findMethod Setting extra type info to overloaded methods may fail with <parameter .../>
17-Oct-2019 09:59:16.972 严重 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultCreatorManager.getCreator Class not found: '?'
17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultCreatorManager.getCreator Names of known classes are: ajaxDataService __Data __System 
17-Oct-2019 09:59:16.972 严重 [http-nio-8080-exec-7] org.directwebremoting.impl.SignatureParser.parse Unexpected Error
	java.lang.SecurityException: Class not found
		at org.directwebremoting.impl.DefaultCreatorManager.getCreator(DefaultCreatorManager.java:185)
		at org.directwebremoting.impl.SignatureParser.findClass(SignatureParser.java:255)
		at org.directwebremoting.impl.SignatureParser.parseDeclarationLine(SignatureParser.java:184)
		at org.directwebremoting.impl.SignatureParser.parse(SignatureParser.java:88)
		at org.directwebremoting.impl.DwrXmlConfigurator.loadSignature(DwrXmlConfigurator.java:474)
		at org.directwebremoting.impl.DwrXmlConfigurator.configure(DwrXmlConfigurator.java:168)
		at org.directwebremoting.impl.StartupUtil.configureFromInitParams(StartupUtil.java:621)
		at org.directwebremoting.impl.StartupUtil.configureContainerFully(StartupUtil.java:687)
		at org.directwebremoting.servlet.DwrServlet.configureContainer(DwrServlet.java:109)
		at org.directwebremoting.servlet.DwrServlet.init(DwrServlet.java:68)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:763)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)

**Comment by chenjiajun1984** [comment]
@giscafer 麻烦帮忙看下

**Comment by giscafer** [comment]
依赖包没更新成功吧

**Comment by xuanke90** [comment]
我也是报这个错，依赖包更新成功了啊

**Comment by xuanke90** [comment]
开发环境运用正常，但生成环境直接启动不了

**Comment by Phoenix-deeplot** [comment]
> 17-Oct-2019 09:59:16.192 信息 [http-nio-8080-exec-7] org.directwebremoting.impl.StartupUtil.logStartup Starting: DwrServlet v3.0.0.116.rc1 on Apache Tomcat/8.5.47 / JDK 1.8.0_121 from Oracle Corporation at /FinalScheduler_Web_exploded
> 17-Oct-2019 09:59:16.957 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DTDEntityResolver.resolveEntity Deprecated public id in dwr.xml. Use:
> 17-Oct-2019 09:59:16.957 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Clash of converters for java.util.Map. Using org.directwebremoting.convert.MapConverter in place of org.directwebremoting.convert.MapConverter
> 17-Oct-2019 09:59:16.957 信息 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Probably not an issue: java.util.List is not available so the list converter will not load. This is only an problem if you wanted to use it.
> 17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultConverterManager.addConverter Clash of converters for java.util.Collection. Using org.directwebremoting.convert.CollectionConverter in place of org.directwebremoting.convert.CollectionConverter
> 17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.SignatureParser.findMethod Setting extra type info to overloaded methods may fail with <parameter .../>
> 17-Oct-2019 09:59:16.972 严重 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultCreatorManager.getCreator Class not found: '?'
> 17-Oct-2019 09:59:16.972 警告 [http-nio-8080-exec-7] org.directwebremoting.impl.DefaultCreatorManager.getCreator Names of known classes are: ajaxDataService __Data __System
> 17-Oct-2019 09:59:16.972 严重 [http-nio-8080-exec-7] org.directwebremoting.impl.SignatureParser.parse Unexpected Error
> java.lang.SecurityException: Class not found
> at org.directwebremoting.impl.DefaultCreatorManager.getCreator(DefaultCreatorManager.java:185)
> at org.directwebremoting.impl.SignatureParser.findClass(SignatureParser.java:255)
> at org.directwebremoting.impl.SignatureParser.parseDeclarationLine(SignatureParser.java:184)
> at org.directwebremoting.impl.SignatureParser.parse(SignatureParser.java:88)
> at org.directwebremoting.impl.DwrXmlConfigurator.loadSignature(DwrXmlConfigurator.java:474)
> at org.directwebremoting.impl.DwrXmlConfigurator.configure(DwrXmlConfigurator.java:168)
> at org.directwebremoting.impl.StartupUtil.configureFromInitParams(StartupUtil.java:621)
> at org.directwebremoting.impl.StartupUtil.configureContainerFully(StartupUtil.java:687)
> at org.directwebremoting.servlet.DwrServlet.configureContainer(DwrServlet.java:109)
> at org.directwebremoting.servlet.DwrServlet.init(DwrServlet.java:68)
> at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
> at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
> at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:763)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
> at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
> at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
> at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> at java.lang.Thread.run(Thread.java:745)



> @giscafer 麻烦帮忙看下
这个项目在idea中怎么启动，貌似启动不了

**Comment by iamBenson13** [comment]
请问最后如何启动了？我也碰到这个问题，大神求解

**Comment by ghost** [comment]
大哥，怎么解决啊，数据库一步步的改，终于算是导入进去了，现在有页面，但是没数据信息，idea报的就是上面的错
